files: ['**/*.js']

exclude_paths: [
  'vendor/assets/javascripts',
  'lib/assets/javascripts'
]

options:
  # enforcing options
  bitwise:    false
  camelcase:  false
  curly:      false
  eqeqeq:     true
  forin:      true
  freeze:     true
  immed:      true
  indent:     2
  latedef:    true
  newcap:     false
  noarg:      true
  noempty:    true
  nonbsp:     true
  nonew:      false
  notypeof:   true
  undef:      true
  unused:     true

  # relaxing options
  asi:        false
  boss:       false
  browser:    true
  devel:      true
  eqnull:     true
  evil:       false
  expr:       true
  jasmine:    true
  jquery:     true
  lastsemic:  true
  laxbreak:   true
  laxcomma:   true
  loopfunc:   false
  scripturl:  false
  sub:        true
  supernew:   true

  globals:
    "_":                       true
    "Backbone":                true
    "gon":                     true
    "Handlebars":              true
    "HandlebarsTemplates":     true
    "ImagePaths":              true
    "jsxc":                    true
    "MBP":                     true
    "Routes":                  true
    "OSM":                     true
    "parse_url":               true
    "punycode":                true
    "qq":                      true

    "loginAs":                 true
    "logout":                  true
    "spec":                    true
    "context":                 true
    "factory":                 true
    "stubView":                true
    "exports":                 true

    "app":                     true
    "Diaspora":                true
    "Mentions":                true
    "PosixBracketExpressions": true
